export const actionTypes = {
  LOG_IN: "LOG_IN",
  LOG_IN_SUCCESS: "LOG_IN_SUCCESS",
  LOG_IN_FAILED: "LOG_IN_FAILED",
  SIGN_UP: "SIGN_UP",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_FAILED: "SIGN_UP_FAILED",
  SIGN_OUT: "SIGN_OUT",
  SET_CURRENT_USER: "SET_CURRENT_USER"
};
